- name: Install node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Copy node exporter service file
  register: node_exporter_service
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: 0644

- name: Enable and check node exporter service
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes
    no_block: yes
